#!/bin/bash

echo "[INFO] Determining which branch we are pushing to..."

branch=`git rev-parse --abbrev-ref HEAD`

echo $branch

echo "[INFO] Current branch: $branch"

if [ "master" == "$branch" ]; then
  echo 'Pushed changes to master'

elif [ "staging" == "$branch" ]; then
  echo 'Pushed changes to staging'

elif [ "development" == "$branch" ]; then
  echo 'Pushed changes to development'
  awk -F '= ' '/CORE_BUILD_NO/{$2=$2+1";"}1' OFS='= ' common/info.py
  git add common/info.py
  echo 'Updated build number...'

else:
  echo 'Pushed changes to branch $branch'
fi

echo "done"
