#!/bin/bash

commit_msg_file=$1
commit_source=$2

branch=`git rev-parse --abbrev-ref HEAD`

# There are multiple commit sources, we are only interested in merge.
if [ "${commit_source}" != merge ]; then
    echo '[INFO] Not a merge commit, not updating build number...'
    exit 0
fi

if [ "master" == "$branch" ]; then
  echo '[INFO] Pushing changes to master'

elif [ "development" == "$branch" ]; then
  echo '[INFO] Merging changes to development, Updated build number...'
  awk -F '= ' '/CORE_BUILD_NO/{$2=$2+1}1' OFS='= ' src/common/info.py > src/common/tmp.py
  mv src/common/tmp.py src/common/info.py
  git add src/common/info.py

else
  echo "[INFO] Pushed changes to branch $branch"
fi
